### ISSUE TITLE
No way to pass options to Renderer when creating app ?

### ISSUE THREAD

**Issue by scarletsky** [pissang/claygl#101]
I want to take the screenshot and I need to pass `preserveDrawingBuffer = true` to the renderer.

But in the source code of App3D:

```js
var rendererOpts = {};
isDomCanvas && (rendererOpts.canvas = dom);
appNS.devicePixelRatio && (rendererOpts.devicePixelRatio = appNS.devicePixelRatio);

var gRenderer = new Renderer(rendererOpts);
```

So, how can I do this ? Create another class App3D by myself ?

**Comment by pissang** [comment]
Thank you for pointing out this problem. Never noticed that.

I've make a commit to fix it. You can use `glAttributes` property to configure preserveDrawingBuffer when creating application.

```js
application.create({
  glAttributes: { preserveDrawingBuffer: true }
});
```

**Comment by scarletsky** [comment]
That's great !
