### ISSUE TITLE
How to map custom attributes in the geometry to the attributes in the vertex shader?

### ISSUE THREAD

**Issue by SixiCat** [pissang/claygl#104]
Hi,

I add a custom attribute in my geometry，but i can't get it in vertex shader. Do i have to use the builtin attributes? 

For example:
```js
lineGeo.attributes.next = new clay.GeometryBase.Attribute('next', 'float', 3, 'NEXT');
`attribute vec3 next : NEXT; `
```
Thanks
Best regards

**Comment by pissang** [comment]
Hi,

You need to use `createAttribute` method to create your own attribute. Like following:

```js
lineGeo.createAttribute('next', 'float', 3, 'NEXT');
`attribute vec3 next : NEXT; `
```

And semantic is not MUST have.

```JS
lineGeo.createAttribute('next', 'float', 3);
`attribute vec3 next; `
```

**Comment by SixiCat** [comment]
Thanks a lot. It works when i don't use semantic .
