### ISSUE TITLE
404 error in some document pages

### ISSUE THREAD

**Issue by chchwy** [pissang/claygl#105]
For examples, I got a 404 in the following pages:
http://docs.claygl.xyz/api/clay.shader.html
http://docs.claygl.xyz/api/clay.texture_.html

Could you please have a look at this? Thanks.

**Comment by ejamshidiasl** [comment]
something strange is here!
1- remove underscore ( _ ) from end of url if it has any underscore.
2- add underscore ( _ ) to url before .html if url has no _
**http://docs.claygl.xyz/api/clay.shader_.html**
**http://docs.claygl.xyz/api/clay.texture.html**
