### ISSUE TITLE
如何设置类似 ECharts GL 中的模型（材质）效果

### ISSUE THREAD

**Issue by privatemiao** [pissang/claygl#131]
你好，我的模型都是 GLTF / GLB 的格式，
大部分都是白模（白色、无贴图）

请问如何配置，让模型呈现出类似 ECharts GL 中的模型的效果。

**Comment by pissang** [comment]
可以使用 https://github.com/pissang/clay-viewer

**Comment by privatemiao** [comment]
![image](https://user-images.githubusercontent.com/1772357/141726159-828c09f3-c24b-4269-8fa6-500454cefdbd.png)
我就是在 clay viewer 上配置的
但是始终达不到 ECharts GL 中  地图上建筑的效果 
![image](https://user-images.githubusercontent.com/1772357/141726291-739da6ec-8b2f-427e-ad31-8b2d8625378b.png)
能不能提供一些配置的参数，或者截图，谢谢   我太喜欢 ECharts 中建筑的渲染效果了。

**Comment by pissang** [comment]
截图中是材质配置成了 metalness: 1 然后 roughness 接近 0，就是金属的材质

**Comment by privatemiao** [comment]
谢谢 确实好很多
![image](https://user-images.githubusercontent.com/1772357/141739530-1c4106c6-7f45-4fa7-9de6-2194b0b4b1d6.png)
