### ISSUE TITLE
If shading type is "unknown" a TypeError is thrown

### ISSUE THREAD

**Issue by schubboy** [pissang/claygl#31]
There is no try/catch to try and fix or report on this error.  On line 425, in the ConvertToPBRMaterial function, there is an early return that does not follow the method signature of returning a tuple of 5 values.  The calling line 638 in the function ConvertMesh requires a tuple return value.  If this does not happen, EG, the early return executes in ConvertToPBRMaterial, the python script throws a TypeError: 'int' object is not iterable.

Not sure what the intention was here, but if you are expecting a the 'unknown' material shading type and doing an early return, at a minimum the calling code should check for that and either try/catch with a descriptive error message, better yet, write the code to recover and continue on.  As it is I cannot decipher what the code-writer's intent was from reading the functions, so some code-comments in there would also be a big improvement.

**Comment by pissang** [comment]
Thanks for the detailed report! Already fixed in https://github.com/pissang/claygl/commit/9ff18618d8d2c70d1801b4f858ba244d6a2d80b2
