### ISSUE TITLE
add eslint

### ISSUE THREAD

**Issue by fuzhenn** [pissang/claygl#37]
Recommend to add eslint config to avoid typos or unused varibles in the first place, like the one [in PR #36 ](https://github.com/pissang/claygl/pull/36/files#diff-85018f5433a4a659adfe6d69d2c191fb)

**Comment by pissang** [comment]
Currently claygl uses jshint https://github.com/pissang/claygl/blob/master/.jshintrc . And I'm afraid both jshint and eslint can't point out typos of method name, like in the link.

**Comment by fuzhenn** [comment]
yeah, indeed
closing
