### ISSUE TITLE
precision problem in Matrix4

### ISSUE THREAD

**Issue by fuzhenn** [pissang/claygl#41]
目前`clay.math.Matrix4`中默认用[`Float32Array`创建的array](https://github.com/pissang/claygl/blob/master/src/math/Matrix4.js#L24)，造成矩阵计算过程中，如果中间结果的精度超过32位float时，会出现精度丢失的问题。

是否考虑把Matrix4改为用普通的数组来实现，在调用gl方法时，再转为Float32Array？

其他的math下的类同理（Matrix*， Vector*）

作为参考，THREE中的[Matrix4](https://github.com/mrdoob/three.js/blob/dev/src/math/Matrix4.js)是基于普通数组来实现的

**Comment by pissang** [comment]
好的，我评估一下 Array，Float32Array 和 Float64Array 之间的差距

**Comment by fuzhenn** [comment]
用geometry.applyTransform转换图形时会出现偏移， 但换用mesh.setLocalTransform就不会
这两个操作应该是等价的吧？
怀疑也是因为Geometry的position用Float32Array存储造成的精度损失

**Comment by pissang** [comment]
https://github.com/pissang/claygl/commit/1401e70e0f0c12ec96e744d07e457fec31ff5264 中将默认的 Float32Array 换为了 Array，测试下来 1w 个 cube 的场景反而有了 20% 左右的性能提升。

attributes 那个没法用 Array 或者 Float64Array，因为 buffer 不支持，如果 applyTransform 也有精度缺失的话，只能在外部处理完再传回去。
