### ISSUE TITLE
Scene.removeFromScene

### ISSUE THREAD

**Issue by fuzhenn** [pissang/claygl#42]
调用scene.removeFromScene(mesh)后，mesh没被移除，依然继续会被绘制
以下就能正常移除：
```js
scene.removeFromScene(mesh);
scene.remove(mesh);
```
是不是应该在removeFromScene中调用一下 this.remove(node) ？

**Comment by pissang** [comment]
这个接口可能有点混淆，现在的逻辑在场景树中添加删除节点统一用 add 和 remove 方法，作用是添加为儿子节点或者从儿子节点中删除，添加/删除的过程会递归遍历所有子孙节点然后用 `addToScene` 和 `removeFromScene` 方法统一添加/删除到场景实例中，这两个方法一般来说是不会直接电泳的
