### ISSUE TITLE
The ground of the drone sample is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [pissang/claygl#45]
I tried to display the [drone](https://sketchfab.com/models/294e79652f494130ad2ab00a13fdbafd) sample with ClayGL.
However, it seems that the display results are different between QTEK and ClayGL.

[ClayGL + drone sample result:](http://jsdo.it/cx20/ogoH)
![image](https://user-images.githubusercontent.com/1833979/35186872-c4ff5978-fe5e-11e7-8a32-2180bbda7f26.png)

[QTEK(QMV.js) + drone sample result:](http://jsdo.it/cx20/GGVv)
![image](https://user-images.githubusercontent.com/1833979/35186880-dac9b352-fe5e-11e7-8345-d6d1cd502d8d.png)

**Comment by pissang** [comment]
This is because StandardMaterial in ClayGL doesn't use the alpha channel in diffuse map.

**Comment by cx20** [comment]
I confirmed that I am improving with the latest library.
http://jsdo.it/cx20/ISCw
![image](https://user-images.githubusercontent.com/1833979/35217055-2fe75c50-ffad-11e7-8de9-55c37826c826.png)
