### ISSUE TITLE
VoxelCorgi.gltf is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [pissang/claygl#47]
I tried to display VoxelCorgi.gltf output by Three.js glTF Exporter with ClayGL.
QTEK displays it without problems, but ClayGL seems to get darker.

[ClayGL + VoxelCorgi.gltf result:](http://jsdo.it/cx20/2xCG)
![image](https://user-images.githubusercontent.com/1833979/35235819-93ff8bdc-ffe8-11e7-9905-abcbbe9cd747.png)

[QTEK + VoxelCorgi.gltf result:](http://jsdo.it/cx20/6mvP)
![image](https://user-images.githubusercontent.com/1833979/35235912-db05050c-ffe8-11e7-993d-1632055f62d8.png)

Is it a problem with the setting of the light?

**Comment by pissang** [comment]
It's strange. I see there is COLOR_0 attribute in VoxelCorgi.gltf. Which is not supported in QTEK

**Comment by pissang** [comment]
The dark color is caused by COLOR_0 attribute of size `3`. Didn't handle this case. Fixed in https://github.com/pissang/claygl/commit/76c4ead3b49f6a542182bc629678010fcf5d465d

**Comment by cx20** [comment]
I confirmed that the problem was solved with the latest version.
[ClayGL + VoxelCorgi.gltf result:](http://jsdo.it/cx20/kRiS)
![image](https://user-images.githubusercontent.com/1833979/35277581-963dc330-008a-11e8-8153-b4245d96b08d.png)
