### ISSUE TITLE
How to use MovingCamera in Polly glTF model

### ISSUE THREAD

**Issue by cx20** [pissang/claygl#49]
I know that [MovingCamera](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/e71e4c5012208fbac9bd3fddb647afa598c16213/polly/project_polly.gltf#L7677) is included in [Polly glTF model](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly).
The following is an example of using MovingCamera.
https://www.youtube.com/watch?v=l7TB1O51X_M

However, I did not know how to use that camera with ClayGL.
http://jsdo.it/cx20/O26Q

If there is a way to use that camera please tell me how to do it.

**Comment by pissang** [comment]
Added `Scene#setMainCamera` interface in the latest v1.0.2. So using the `MovingCamera` can be simply written as:
```js
app.loadModel('../assets/models/polly/project_polly.gltf').then(function (result) {
    // Use the moving camera as main camera.
    app.scene.setMainCamera(result.cameras[1]);
});
```
Here is a full example http://examples.claygl.xyz/examples/basicGLTFCameraAnimation.html

**Comment by cx20** [comment]
I confirmed that MovingCamera can be used with the latest version of ClayGL.
http://jsdo.it/cx20/QTHw
