### ISSUE TITLE
AmbientLight contructor

### ISSUE THREAD

**Issue by rubydesign** [pissang/claygl#59]
The applications `createAmbientLight` does some parsing and checking to create an AmbientLight.

This code can more less directly go into the AmbientLight constructor. As it checks for null this means no change to the api. Just easier to use the class.

If you want i can make the change

**Comment by pissang** [comment]
Not sure if I understand you correctly. The constructor doesn’t do null checking on properties

**Comment by pissang** [comment]
If you mean adding the null checking in the AmbientLight constructor. Yeah i think it will be better. You can make a pull request about this. Thanks!

**Comment by pissang** [comment]
Or do the validation and color parsing in the uniformTemlates?

**Comment by rubydesign** [comment]
Sorry, what are uniformTemplates?

**Comment by rubydesign** [comment]
Had a little look at the uniformTemplates and also the whole extend and default mechanism.
That's a little too deep water at the moment.
