### ISSUE TITLE
[discussion] move TBN to vertex shader

### ISSUE THREAD

**Issue by fuzhenn** [pissang/claygl#64]
探讨：

目前standard.glsl中，TBN是在fragment shader中计算和应用的。

如果转为在vertex shader中计算TBN，并将所需的normal/light direction/eye direction等在vertex shader中提前转换为TBN坐标后再传递给fragment shader, 这样fragment shader中就不需要做TBN矩阵乘法，应该能提升一些性能。

只是我一点不成熟的想法，不知道是否可行：
* 如果有parallax occlusion或normal map时，在vertex shader中计算TBN，并将相关的uniform和TBN相乘，传递给fragment shader，例如light direction，view direction等
* 在fragment shader中计算时，直接应用vertex shader中提前计算好的TBN uniform

祝好

**Comment by pissang** [comment]
这一块我没有具体的对比过，下面就我的一些想法

+ tbn 复杂点的计算都已经在 vs 里完成，fs 里只是直接拿三个向量组成了一个矩阵

+ varying 是需要插值得到每个像素的变量的，如果在 vs 里组成 tbn，这个 mat3 在插值的时候会比两个 vec3 的 v_Tangent 和 v_Bitangent 多出一个 vec3（v_Normal 不管怎么样都是会传的），性能上不见得会更好。

具体的性能测试可能要很极端才能看出来，我待会写个试试

**Comment by pissang** [comment]
如果你指的是在vs 里就计算好 tbn 乘过的 normal 的话：

早期硬件条件不够的时候是会在 vs 里尽量计算好光照这些东西，但是 vs 里计算效果跟 per pixel 的 fs 是没法比的，因为 vs 传到 fs 里的 varying 是顶点间插值的。特别是 normal map 和 parallax occlusion map，因为这两个原先就是为了追求 per pixel 精度的几何光照细节。

如果是在 vs 里计算好 tbn 传给 fs 的话：

我没写过具体的性能对比 case，但是传 mat3 需要每个像素插值计算三个 vec3，传 v_Tangent 和 v_Bitangent 只需要插值计算两个（v_Normal 不管怎么样都是要传的），fs 里组成 tbn 也支持一个创建 mat3 的操作，所以放 vs 里做性能不一定会更好。不过这两个之间区别可能要写非常极端的 case 才能对比出来

**Comment by fuzhenn** [comment]
不再转换normal, 改为转换viewDir, lightDir等

vs中
* 计算tbn的逆矩阵 itbn = invert(tbn)
* varying tbnLightDir = itbn * lightDir

fs中
* 在计算光照时，例如 dot(N, L)， N是从normal纹理中取出的值，L是上一步中的tbnLightDir

这样能省略一些掉fs里的tbn乘法计算，例如：
https://github.com/pissang/claygl/blob/master/src/shader/source/standard.glsl#L329
https://github.com/pissang/claygl/blob/master/src/shader/source/standard.glsl#L396

**Comment by pissang** [comment]
那需要转换很多的变量，每个灯光的 direction 都要转换到这个 tangent space

**Comment by fuzhenn** [comment]
确实，多了不少varying
确实很难讲这个改进是否有价值，矩阵乘法速度也不慢，先关闭啦~
