### ISSUE TITLE
can't run script on mac/python 3.6.4

### ISSUE THREAD

**Issue by electroheadfx** [pissang/claygl#65]
I installed python 3.6.4,
I run script with command: python3 fbx2gltf.py
I have message:
"You need to copy the content in compatible subfolder under /lib/python<version> into your python install folder such as "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages" folder."

**Comment by pissang** [comment]
Because the FBX SDK is compiled with python3.3  So only this version is supported.

**Comment by electroheadfx** [comment]
ah ok. Is a v 3.3.0 ~ 3.3.7 ?

**Comment by pissang** [comment]
Yes

**Comment by Vege1994** [comment]
How can I compiled FBX SDK with python3.6? I want to use tools/fbx2gltf.py by Python3.6
