### ISSUE TITLE
Converted OBJ is missing textures in glTF 

### ISSUE THREAD

**Issue by nickkraakman** [pissang/claygl#67]
Hi,

On the [KhronosGroup page](https://github.com/KhronosGroup/glTF/#converters-and-exporters) it is mentioned that your converter also accepts OBJ and COLLADA files. However, when I use an OBJ as input file, the glTF or GLB output never contains the texture, see [bunny.zip](https://github.com/pissang/claygl/files/1771185/bunny.zip)

This makes the converter unusable for OBJ files.

Nick

**Comment by pissang** [comment]
It seems the FBX SDK can't read the texture in this OBJ file. I've tried some other OBJ files before and it works fine.

**Comment by pissang** [comment]
I found in the `bunny.obj` the code is `mtllib bunny2.mtl` but the file name is `bunny.mtl`. It works fine if I change it to `mtllib bunny2.mtl`. Not sure if it's the problem when exported from blender.

**Comment by nickkraakman** [comment]
Hi @pissang,

Thanks so much for the quick reply! Indeed, renaming the material to `bunny2.mtl` worked! I used many OBJs (from Sketchfab and TurboSquid) for testing, but it seems pretty difficult to find a properly formatted OBJ which correctly references its materials and textures. 

This issue can be closed.

Nick
