### ISSUE TITLE
How to apply environment map to the glTF

### ISSUE THREAD

**Issue by cx20** [pissang/claygl#69]
I tested the following [model](https://github.com/emackey/glTF-Sample-Models/tree/normal-tangent-mirror-test/2.0/NormalTangentTest) with [gltf-test](https://github.com/cx20/gltf-test#agi-sample-models).
However, since the environment map is not applied correctly, part of the model is displayed in black.

[ClayGL + NormalTangentTest.gltf result:](https://cx20.github.io/gltf-test/examples/claygl/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/36931942-21194136-1f04-11e8-9adc-750e0316db2b.png)

[Expected result of NormalTangentTest.gltf:](https://github.com/emackey/glTF-Sample-Models/tree/normal-tangent-mirror-test/2.0/NormalTangentTest)
![image](https://user-images.githubusercontent.com/1833979/36931981-4b39a0e0-1f05-11e8-9394-fc15aa9617b6.png)

Please tell me how to apply environment map to glTF if you like.

**Comment by pissang** [comment]
Hi @cx20 . You can use [createAmbientCubemapLight](http://docs.claygl.xyz/api/clay.application.App3D.html#createAmbientCubemapLight) to use environment map. Here is a basic example http://examples.claygl.xyz/examples/basicModelPBR.html

**Comment by cx20** [comment]
I was able to apply the environment map to glTF. 
[ClayGL + NormalTangentTest.gltf result:](https://cx20.github.io/gltf-test/examples/claygl/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/36935481-a49d8f62-1f3b-11e8-86a0-170cf5bb30dd.png)

Thanks!
