### ISSUE TITLE
About cubemap roughness when prefiltering cubemap

### ISSUE THREAD

**Issue by fuzhenn** [pissang/claygl#70]
这里不晓得是不是我的理解问题，生成prefilter cubemap时， 这里的roughness的是否应该是 `1 / (mipmapNum - 1)`

https://github.com/pissang/claygl/blob/master/src/util/cubemap.js#L127

**Comment by pissang** [comment]
是的...手误了，刚好 targets.length 和 mipmapNum 数字差不多
