### ISSUE TITLE
Vertex colors support

### ISSUE THREAD

**Issue by xAlien95** [pissang/claygl#85]
The FBX to glTF2.0 Converter provided is one of the best actually available on the web.
Is vertex colors support planned for it? glTF format handles vertex colors buffers in mesh attributes:

```js
{
    "meshes": [
        {
            "name": "MESH_NAME",
            "primitives": [
                {
                    "attributes": {
                        "COLOR_0": 5,
                        "NORMAL": 2,
                        "POSITION": 1,
                        "TANGENT": 3,
                        "TEXCOORD_0": 4
                    },
                    "indices": 0,
                    "material": 2
                }
            ]
        },
        ...
    ],
    ...
}
```

**Comment by xAlien95** [comment]
Pull request #87 adds this enhancement.

**Comment by xAlien95** [comment]
@pissang, since the majority of models uses 8-bit per channel RGBA vertex colors, are you interested in adding such feature in your converter?

If so, commit xAlien95@f2f7c28f95f4c2dd66e0de5ce5e332b5d109f71a adds this with the optional `--no8bitcolors` command line argument, with default to `False` (if not specified normalized 8-bit RGBA vertex colors will be stored instead of the float4 ones).

Size differences of the exported models can be huge: the model I'm working on has an exported .bin size of 461 kB with float4 vertex colors and 345 kB with 8-bit vertex colors, 0.25% less data.

I also fixed some minor typos, such as a misspelled `lGLTFAccessor` and a double declared `GL_REPEAT` global variable.

If you are interested I'll make a pull-request. If you aren't you can close this issue, since vertex colors are now supported. Thanks.

**Comment by pissang** [comment]
@xAlien95 Sorry for the late reply. A pull request will great!! Thanks again!

**Comment by pissang** [comment]
@xAlien95 BTW do you have the case that vertex color needs to be float type. Perhaps we can always store the vertex color in rgba8 format.

**Comment by xAlien95** [comment]
> Perhaps we can always store the vertex color in rgba8 format.

@pissang, I initially implemented them as Float4 because my .dae models had them stored as Float4. RGBA8 format should be fine, I will remove the optional command line argument.

Pull request #88 is live now. You can close this issue, thanks!
